In [18]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [19]:
from RAVEN.pe.appr_poly_utils import Ref_Func as ref_func
import torch

SyntaxError: invalid syntax (appr_poly_utils.py, line 15)

In [35]:
mode = "exp"

In [36]:
func = ref_func(mode).inst()

In [37]:
print(func)

<bound method Ref_Func.ref_exp of <RAVEN.pe.appr_poly_utils.Ref_Func object at 0x1218d9a90>>


In [38]:
func_out = func(torch.Tensor([0, 1]))

In [39]:
print(func_out)

tensor([1.0000, 2.7183])


In [15]:
import math

for y in range(800):
    x = (y+1)/100
#     a = (x-1)**1 - 1/2*(x-1)**2 + 1/3*(x-1)**3 - 1/4*(x-1)**4 + 1/5*(x-1)**5 - 1/6*(x-1)**6 + 1/7*(x-1)**7 - 1/8*(x-1)**8
    
    a = math.log(7) + 1/1*(x-7)**1/7**1 - 1/2*(x-7)**2/7**2 + 1/3*(x-7)**3/7**3
#     - 1/4*(x-7)**4/7**4
    
    print(y, "th:", "input:", x, "output", math.log(x), "error:", a - math.log(x))

0 th: input: 0.01 output -4.605170185988091 error: 4.722029655743112
1 th: input: 0.02 output -3.912023005428146 error: 4.033159012598134
2 th: input: 0.03 output -3.506557897319982 error: 3.6319643311177634
3 th: input: 0.04 output -3.2188758248682006 error: 3.348546580337508
4 th: input: 0.05 output -2.995732273553991 error: 3.1296612515694595
5 th: input: 0.06 output -2.8134107167600364 error: 2.9515918240272057
6 th: input: 0.07 output -2.659260036932778 error: 2.8016871859880914
7 th: input: 0.08 output -2.5257286443082556 error: 2.6723957535190594
8 th: input: 0.09 output -2.4079456086518722 error: 2.5588466022164176
9 th: input: 0.1 output -2.3025850929940455 error: 2.457713900941487
10 th: input: 0.11 output -2.2072749131897207 error: 2.3666254713801167
11 th: input: 0.12 output -2.120263536200091 error: 2.2838297863244033
12 th: input: 0.13 output -2.0402208285265546 error: 2.2079967181066493
13 th: input: 0.14 output -1.9661128563728327 error: 2.138092338761479
14 th: input: 

278 th: input: 2.79 output 1.0260415958332743 error: 0.0650663073522626
279 th: input: 2.8 output 1.0296194171811581 error: 0.06429073187415524
280 th: input: 2.81 output 1.0331844833456545 error: 0.063523421783517
281 th: input: 2.82 output 1.0367368849500223 error: 0.06276429228799252
282 th: input: 2.83 output 1.0402767116551463 error: 0.062013259557601286
283 th: input: 2.84 output 1.0438040521731147 error: 0.06127024071115872
284 th: input: 2.85 output 1.0473189942805592 error: 0.060535153802936836
285 th: input: 2.86 output 1.0508216248317612 error: 0.05980791780955785
286 th: input: 2.87 output 1.0543120297715298 error: 0.059088452617116705
287 th: input: 2.88 output 1.0577902941478545 error: 0.05837667900852739
288 th: input: 2.89 output 1.0612565021243408 error: 0.057672518651089355
289 th: input: 2.9 output 1.0647107369924282 error: 0.05697589408426529
290 th: input: 2.91 output 1.0681530811834012 error: 0.05628672870767493
291 th: input: 2.92 output 1.0715836162801904 error:

578 th: input: 5.79 output 1.7561322915849038 error: 0.0002592850700209315
579 th: input: 5.8 output 1.7578579175523736 error: 0.00025048223180257345
580 th: input: 5.81 output 1.7595805708638197 error: 0.00024191152482666567
581 th: input: 5.82 output 1.7613002617433464 error: 0.0002335685558929601
582 th: input: 5.83 output 1.763017000362401 error: 0.00022544898445731043
583 th: input: 5.84 output 1.7647307968401356 error: 0.00021754852227195975
584 th: input: 5.85 output 1.766441661243765 error: 0.00020986293302538428
585 th: input: 5.86 output 1.7681496035889213 error: 0.00020238803198968647
586 th: input: 5.87 output 1.7698546338400052 error: 0.00019511968566754412
587 th: input: 5.88 output 1.7715567619105355 error: 0.00018805381144448852
588 th: input: 5.89 output 1.7732559976634952 error: 0.00018118637724096054
589 th: input: 5.9 output 1.7749523509116738 error: 0.00017451340117125014
590 th: input: 5.91 output 1.776645831418007 error: 0.000168030951203324
591 th: input: 5.92 o

760 th: input: 7.61 output 2.0294631718735947 error: 1.347961126230146e-05
761 th: input: 7.62 output 2.030776369698555 error: 1.4370221675719108e-05
762 th: input: 7.63 output 2.0320878452963655 error: 1.5303758948093105e-05
763 th: input: 7.64 output 2.033397603178429 error: 1.6281542579044128e-05
764 th: input: 7.65 output 2.0347056478384444 error: 1.7304909774473742e-05
765 th: input: 7.66 output 2.0360119837525 error: 1.837521534975295e-05
766 th: input: 7.67 output 2.0373166153791646 error: 1.949383163912799e-05
767 th: input: 7.68 output 2.038619547159581 error: 2.0662148405126146e-05
768 th: input: 7.69 output 2.0399207835175526 error: 2.1881572746185185e-05
769 th: input: 7.7 output 2.0412203288596382 error: 2.3153529008279605e-05
770 th: input: 7.71 output 2.0425181875752383 error: 2.4479458695214618e-05
771 th: input: 7.72 output 2.0438143640366846 error: 2.5860820378031946e-05
772 th: input: 7.73 output 2.0451088625993306 error: 2.7299089607524252e-05
773 th: input: 7.74 ou

In [17]:
math.pow(0.1,0)

1.0

In [53]:
import torch
class square(torch.nn.Module):
    def __init__(self):
        super(square, self).__init__()
    
    def forward(self, input):
        return input * input + input * input * input


a = torch.tensor(0.45, dtype=torch.float64, requires_grad=True)
print(a.grad)
output = square()
loss = output(a)
print(loss)
loss.backward()
print(a.grad)

# a_1 = a * 1
# print(a_1)
# a_2 = a * a
# print(a_2)
# a_3 = a * a * a
# print(a_3)
# a_4 = a * a * a * a
# print(a_4)

# loss = (a_1 + a_2 + a_3 + a_4)
# print(loss)
# loss.backward()

# print(a.grad)


None
tensor(0.2936, dtype=torch.float64, grad_fn=<AddBackward0>)
tensor(1.5075, dtype=torch.float64)


In [2]:
a = torch.tensor([1.5])
a >> 2

tensor([0.3750])

In [3]:
a = torch.tensor([1, 0, 1, 0])
b = torch.tensor([1, 1, 0, 0])
print(a | b)

tensor([1, 1, 1, 0])
